Resources:
  AdditionalHydraTestPermissions:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - Ref: HydraTestInvocationRole
      PolicyName: AdditionalHydraTestPermissions
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - lambda:GetFunctionConfiguration
              - lambda:GetFunction
              - lambda:InvokeFunction
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
          - Action:
              - events:DescribeRule
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/*"
          - Action:
              - lambda:ListEventSourceMappings
            Effect: Allow
            Resource: "*"
          - Action:
              - cloudformation:DescribeStacks
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/RegionsReconPythonLambda/*"
          
          - Action:
              - dynamodb:GetItem
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/buildables"

          - Action:
              - iam:GetRolePolicy
            Effect: Allow
            Resource: "*"
          - Action:
              - iam:GetRole
            Effect: Allow
            Resource: "*"